<a href="https://colab.research.google.com/github/hrshankar2002/Pytorch-notes/blob/main/pytorch_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**

<img src = "https://editor.analyticsvidhya.com/uploads/64798tensor.png">

**Tensor Visualization of shape (4,1,2,3)**

<ul>
  <li>The first dimension (4) represents the batch size.</li>
  <li>The second dimension (1) represents the number of channels.
</li>
  <li>The third dimension (2) represents the height.
</li>
<li>The fourth dimension (3) represents the width.
</li>
</ul>

<pre>[
  [  # Batch 1
    [  # Channel 1
      [1, 2, 3],  # Row 1
      [4, 5, 6]   # Row 2
    ]
  ],
  [  # Batch 2
    [  # Channel 1
      [7, 8, 9],   # Row 1
      [10, 11, 12]  # Row 2
    ]
  ],
  [  # Batch 3
    [  # Channel 1
      [13, 14, 15],   # Row 1
      [16, 17, 18]    # Row 2
    ]
  ],
  [  # Batch 4
    [  # Channel 1
      [19, 20, 21],   # Row 1
      [22, 23, 24]    # Row 2
    ]
  ]
]</pre>


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector[1]

tensor(7)

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [3, 4]])
MATRIX

tensor([[7, 8],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0][0]

tensor(7)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3], [3,4,5], [4,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][0][0]

tensor(1)

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7050, 0.0469, 0.1979, 0.8017],
        [0.9765, 0.7703, 0.8947, 0.4880],
        [0.8319, 0.7132, 0.2405, 0.9959]])

In [ ]:
random_image_size_tensor = torch.rand(size = (224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
net = random_tensor*zeros
net

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
net = random_tensor*ones
net

tensor([[0.7050, 0.0469, 0.1979, 0.8017],
        [0.9765, 0.7703, 0.8947, 0.4880],
        [0.8319, 0.7132, 0.2405, 0.9959]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device="cpu",
                               requires_grad=False
                               )
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.int32,
                               device="cpu",
                               requires_grad=False
                               )
int_32_tensor.dtype

torch.int32

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
long_32_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.long,
                               device="cpu",
                               requires_grad=False
                               )
int_32_tensor.dtype

torch.int32

In [ ]:
float_32_tensor * long_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3, 4)
print(some_tensor.dtype, some_tensor.device, some_tensor.shape, sep="\n")

torch.float32
cpu
torch.Size([3, 4])


In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 249 µs, sys: 49 µs, total: 298 µs
Wall time: 1.92 ms


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value

CPU times: user 253 µs, sys: 51 µs, total: 304 µs
Wall time: 342 µs


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 68 µs, sys: 14 µs, total: 82 µs
Wall time: 84.6 µs


tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [ ]:
tensor_A = torch.tensor([ [1,2],
                          [4,5],
                          [2,3]
                         ])
tensor_B = torch.tensor([ [1,2],
                          [3,4],
                          [5,6]
                         ])
torch.mm(tensor_A, tensor_B.T).shape # transpose

torch.Size([3, 3])

In [ ]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean() # mean not working for int64 (default) hence type converted to float32

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

***Reshaping a tensor***

In [ ]:
x = torch.arange(1., 10.)
x_reshaped = x.reshape(1,9)
x, x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
z = x.view(1, 9)
x, z

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
# x and z share same memory
z[:, 0]=10
x, z

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]))

In [ ]:
3# Create a tensor with shape (2, 3, 4)
tensor = torch.randn(2, 3, 4)

# Reshape the tensor to have shape (6, 4)
reshaped_tensor = tensor.view(6, 4)

#tensor, reshaped_tensor
tensor[:, 0]=10
tensor, tensor[1,1]

(tensor([[[10.0000, 10.0000, 10.0000, 10.0000],
          [ 0.1258,  0.5353,  0.9599,  1.2445],
          [-1.6477, -0.1731,  1.2372, -0.1968]],
 
         [[10.0000, 10.0000, 10.0000, 10.0000],
          [-0.1639,  0.4497, -0.1431, -0.2207],
          [-0.4872, -1.2810,  0.0640,  0.3124]]]),
 tensor([-0.1639,  0.4497, -0.1431, -0.2207]))

***Stacking a tensor***

In [ ]:
x_stack1 = torch.stack([x, x, x, x], dim=0)
x_stack2 = torch.stack([x, x, x, x], dim=1)
x, x_stack1, x_stack2

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([[10., 10., 10., 10.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.]]))

In [ ]:
tensor1 = torch.tensor([[[1, 2],
                         [3, 4]],

                        [[5, 6],
                         [7, 8]]])

tensor2 = torch.tensor([[[9, 10],
                         [11, 12]],

                        [[13, 14],
                         [15, 16]]])

stacked_tensor1 = torch.stack([tensor1, tensor2], dim=0)
stacked_tensor2 = torch.stack([tensor1, tensor2], dim=1)
stacked_tensor3 = torch.stack([tensor1, tensor2], dim=3)

In [ ]:
tensor1, tensor2, stacked_tensor1, stacked_tensor2, stacked_tensor3

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 tensor([[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]),
 tensor([[[[ 1,  2],
           [ 3,  4]],
 
          [[ 5,  6],
           [ 7,  8]]],
 
 
         [[[ 9, 10],
           [11, 12]],
 
          [[13, 14],
           [15, 16]]]]),
 tensor([[[[ 1,  2],
           [ 3,  4]],
 
          [[ 9, 10],
           [11, 12]]],
 
 
         [[[ 5,  6],
           [ 7,  8]],
 
          [[13, 14],
           [15, 16]]]]),
 tensor([[[[ 1,  9],
           [ 2, 10]],
 
          [[ 3, 11],
           [ 4, 12]]],
 
 
         [[[ 5, 13],
           [ 6, 14]],
 
          [[ 7, 15],
           [ 8, 16]]]]))

***Squeezing and Unsqueezing a tensor***

<img src="https://blog.kakaocdn.net/dn/1Qjao/btrcc4Yrj0L/P6DAjvSXpCVuIFj84OtHiK/img.png" width="700">

<img src="https://i0.wp.com/theneuralblog.com/wp-content/uploads/2023/12/squeeze-tensors.png?resize=560%2C431&ssl=1" width="700">

In [ ]:
stacked_tensor3.shape

torch.Size([2, 2, 2, 2])

In [ ]:
x_reshaped, x_reshaped.squeeze()

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [ ]:
x_reshaped.shape, x_reshaped.squeeze().shape

(torch.Size([1, 9]), torch.Size([9]))

In [ ]:
(x_reshaped.squeeze()).unsqueeze(dim=0)

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

***Permuting tensors***

In [ ]:
x = torch.randn(2, 3, 5)
x_perm = torch.permute(x, (2, 0, 1)) # 2nd dim comes 1st, 0th dim 2nd, 1st dim 3rd
x.shape, x_perm.shape

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [ ]:
print(x)

tensor([[[-1.9170, -0.0594, -0.5812, -0.4896, -0.3522],
         [ 0.6730,  1.3976,  0.6304, -1.0862, -0.3625],
         [ 0.2789, -1.2767,  0.0529, -0.9173, -1.7285]],

        [[-1.1497,  1.5870,  0.1969,  0.2979, -0.7685],
         [ 1.1044, -0.5354,  0.6982,  0.2495, -0.6020],
         [-0.3762,  1.1975, -1.5831, -0.5279, -1.4658]]])


In [ ]:
x[0,0,0]

tensor(-1.9170)

***Indexing on tensors***

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][1][0]

tensor(4)

In [ ]:
x[:, :, 1] # get all values of 0th  and 1st dim

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1] # same as x[0][1][0] but with a []

tensor([5])

In [ ]:
x[0, 0, :] # get index 0 of 0th and 1st dim and all values of 2nd dim

tensor([1, 2, 3])

In [ ]:
# index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

***Pytorch tensors & numpy***

In [ ]:
# numpy array to tensor
import numpy as np
import torch

arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor, arr.dtype, tensor.dtype
# default dtype of tensor is float32 but numpy -> tensor is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32)

In [ ]:
arr = arr + 1
arr, tensor # changing array doesn't affect tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to numpy
tensor1 = torch.ones(7)
np_tensor = tensor1.numpy()
tensor1.dtype, np_tensor.dtype

(torch.float32, dtype('float32'))

In [ ]:
tensor1 = tensor1 + 1
tensor1, np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

***Reproducibility***

In [ ]:
random_seed = 42

torch.manual_seed(random_seed)
rand_c = torch.rand(3, 4)

torch.manual_seed(random_seed)
rand_d  = torch.rand(3, 4)

print(rand_c)
print(rand_d)
print(rand_c == rand_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


***Running tensors & pytorch objects on GPU***

In [ ]:
!nvidia-smi

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')